#!/bin/env bash

set -e

usage(){
    echo "$0 [ tests | setup ]"
    exit 0
}

_tests() {
    if [[ "x`which locust`" == "x" ]]; then
        echo Activate virtual environment for this project running \"run setup\"
        return 1
    fi

    echo Starting main instance...
    locust --config=configs/main.conf &>logs/main.log &

    sleep 2

    echo Starting nodes...
    for i in {1..5}; do (locust --config=configs/nodes.conf &>logs/node$i.log &) ; done

    echo "\

Done test start-up. Check the logs for additional information.
"
}

_setup() {
    [ ! -d ".venv" ] && python3 -m venv .venv
    . .venv/bin/activate
    pip install -r requirements.txt
    echo "\


__________

Setup done 👍
Run \". .venv/bin/activate\" to activate Python virtual environment on project directory ($PWD)
"
}

[ $# -gt 1 ] && usage

case "$1" in
	tests|setup)
		_$1
		;;
	*)
		usage
		;;
esac
